### PR TITLE
Upgrade to Node 20

### PR DESCRIPTION
**Pull request by jonathanlinat**
This PR aims to resolve this issue: https://github.com/FranzDiebold/github-env-vars-action/issues/59

## Approach

- Upgrade the whole app to `Node` 20
- Add `Node` 20 as a default engine (`package.json`)
- Set `Node` 20 as the default `NVM` version (`.nvmrc`)
- Upgrade some of the `NPM` dependencies to their latest available version
- Add a new `make` command to audit and fix `NPM` dependency vulnerabilities

### CODE REVIEW

**Comment by meabed** [comment]
@FranzDiebold would you be able to merge this soon? thank you

**Comment by jonathanlinat-altitudesports** [comment]
@FranzDiebold Hey! Is there any chance of getting this PR merged soon? Thank you.

**Comment by jonathanlinat** [comment]
@FranzDiebold Hey! Is there any chance of getting this PR merged soon? Thank you.

**Comment by FranzDiebold** [comment]
Thanks @jonathanlinat ! 💪

**Pull request merged**
