### PR TITLE
Expose pull request id as CI_PR_NUMBER and CI_PR_ID

### PR DESCRIPTION
**Pull request by iamstarkov**
Right now the closest this action offers `CI_REF_NAME_SLUG` which is `42-merge`, but its not clean and more importantly cannot be used in numerical contexts which would benefit from having that as `42`. if current event is not a pull-request, it should be empty

### CODE REVIEW

**Comment by iamstarkov** [comment]
hmm, I can't see neither  CI_PR_NUMBER nor CI_PR_ID printed in the demo workflows.

**Comment by iamstarkov** [comment]
fixed

**Comment by FranzDiebold** [comment]
@iamstarkov Thanks for the improvement! 👍

**Comment by iamstarkov** [comment]
@FranzDiebold happy to help out

**Pull request merged**
